/* Generated by Cython 0.9.8 on Sun Jun 20 23:49:41 2010 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifndef DL_EXPORT
  #define DL_EXPORT(t) t
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02060000
  #define Py_REFCNT(ob) (((PyObject*)(ob))->ob_refcnt)
  #define Py_TYPE(ob)   (((PyObject*)(ob))->ob_type)
  #define Py_SIZE(ob)   ((PyVarObject*)(ob))->ob_size)
  #define PyVarObject_HEAD_INIT(type, size) \
          PyObject_HEAD_INIT(type) size,

  typedef struct {
       void *buf;
       Py_ssize_t len;
       int readonly;
       const char *format;
       int ndim;
       Py_ssize_t *shape;
       Py_ssize_t *strides;
       Py_ssize_t *suboffsets;
       Py_ssize_t itemsize;
       void *internal;
  } Py_buffer;

  #define PyBUF_SIMPLE 0
  #define PyBUF_WRITABLE 0x0001
  #define PyBUF_LOCK 0x0002
  #define PyBUF_FORMAT 0x0004
  #define PyBUF_ND 0x0008
  #define PyBUF_STRIDES (0x0010 | PyBUF_ND)
  #define PyBUF_C_CONTIGUOUS (0x0020 | PyBUF_STRIDES)
  #define PyBUF_F_CONTIGUOUS (0x0040 | PyBUF_STRIDES)
  #define PyBUF_ANY_CONTIGUOUS (0x0080 | PyBUF_STRIDES)
  #define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)
#endif
#if PY_MAJOR_VERSION < 3
  #define __Pyx_BUILTIN_MODULE_NAME "__builtin__"
#else
  #define __Pyx_BUILTIN_MODULE_NAME "builtins"
#endif
#if PY_MAJOR_VERSION >= 3
  #define Py_TPFLAGS_CHECKTYPES 0
  #define Py_TPFLAGS_HAVE_INDEX 0
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyBaseString_Type            PyUnicode_Type
  #define PyString_Type                PyBytes_Type
  #define PyInt_Type                   PyLong_Type
  #define PyInt_Check(op)              PyLong_Check(op)
  #define PyInt_CheckExact(op)         PyLong_CheckExact(op)
  #define PyInt_FromString             PyLong_FromString
  #define PyInt_FromUnicode            PyLong_FromUnicode
  #define PyInt_FromLong               PyLong_FromLong
  #define PyInt_FromSize_t             PyLong_FromSize_t
  #define PyInt_FromSsize_t            PyLong_FromSsize_t
  #define PyInt_AsLong                 PyLong_AsLong
  #define PyInt_AS_LONG                PyLong_AS_LONG
  #define PyInt_AsSsize_t              PyLong_AsSsize_t
  #define PyInt_AsUnsignedLongMask     PyLong_AsUnsignedLongMask
  #define PyInt_AsUnsignedLongLongMask PyLong_AsUnsignedLongLongMask
  #define PyNumber_Divide(x,y)         PyNumber_TrueDivide(x,y)
#else
  #define PyBytes_Type                 PyString_Type
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyMethod_New(func, self, klass) PyInstanceMethod_New(func)
#endif
#ifndef __stdcall
  #define __stdcall
#endif
#ifndef __cdecl
  #define __cdecl
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#define __PYX_HAVE_API__dystopia
#include "dystopia.h"


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s; long n; char is_unicode; char intern; char is_identifier;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#if PY_MAJOR_VERSION < 3
#define __Pyx_PyBytes_FromString PyString_FromString
#define __Pyx_PyBytes_AsString   PyString_AsString
#else
#define __Pyx_PyBytes_FromString PyBytes_FromString
#define __Pyx_PyBytes_AsString   PyBytes_AsString
#endif

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static const char * __pyx_cfilenm= __FILE__;
static const char *__pyx_filename;
static const char **__pyx_f;

static INLINE void __Pyx_RaiseArgtupleTooLong(Py_ssize_t num_expected, Py_ssize_t num_found); /*proto*/

static int __Pyx_CheckKeywordStrings(PyObject *kwdict, const char* function_name, int kw_allowed); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

static int __Pyx_SetVtable(PyObject *dict, void *vtable); /*proto*/

static void __Pyx_AddTraceback(const char *funcname); /*proto*/

/* Type declarations */

/* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":48
 * LCKNB = IDBOLCKNB
 * 
 * cdef class database:             # <<<<<<<<<<<<<<
 * 	cdef TCIDB *db
 * 
 */

struct __pyx_obj_8dystopia_database {
  PyObject_HEAD
  struct __pyx_vtabstruct_8dystopia_database *__pyx_vtab;
  TCIDB *db;
};


struct __pyx_vtabstruct_8dystopia_database {
  PyObject *(*__throw_exception)(struct __pyx_obj_8dystopia_database *);
};
static struct __pyx_vtabstruct_8dystopia_database *__pyx_vtabptr_8dystopia_database;
/* Module declarations from dystopia */

static PyTypeObject *__pyx_ptype_8dystopia_database = 0;


/* Implementation of dystopia */


static char __pyx_k___init__[] = "__init__";
static char __pyx_k___del__[] = "__del__";
static char __pyx_k___len__[] = "__len__";
static char __pyx_k_open[] = "open";
static char __pyx_k_close[] = "close";
static char __pyx_k_path[] = "path";
static char __pyx_k_fsiz[] = "fsiz";
static char __pyx_k_put[] = "put";
static char __pyx_k_out[] = "out";
static char __pyx_k_get[] = "get";
static char __pyx_k_vanish[] = "vanish";
static char __pyx_k_tune[] = "tune";
static char __pyx_k_setcache[] = "setcache";
static char __pyx_k_setfwmmax[] = "setfwmmax";
static char __pyx_k_sync[] = "sync";
static char __pyx_k_optimize[] = "optimize";
static char __pyx_k_READER[] = "READER";
static char __pyx_k_WRITER[] = "WRITER";
static char __pyx_k_CREAT[] = "CREAT";
static char __pyx_k_TRUNC[] = "TRUNC";
static char __pyx_k_NOLCK[] = "NOLCK";
static char __pyx_k_LCKNB[] = "LCKNB";

static PyObject *__pyx_kp___init__;
static PyObject *__pyx_kp___del__;
static PyObject *__pyx_kp___len__;
static PyObject *__pyx_kp_open;
static PyObject *__pyx_kp_close;
static PyObject *__pyx_kp_path;
static PyObject *__pyx_kp_fsiz;
static PyObject *__pyx_kp_put;
static PyObject *__pyx_kp_out;
static PyObject *__pyx_kp_get;
static PyObject *__pyx_kp_vanish;
static PyObject *__pyx_kp_tune;
static PyObject *__pyx_kp_setcache;
static PyObject *__pyx_kp_setfwmmax;
static PyObject *__pyx_kp_sync;
static PyObject *__pyx_kp_optimize;
static PyObject *__pyx_kp_READER;
static PyObject *__pyx_kp_WRITER;
static PyObject *__pyx_kp_CREAT;
static PyObject *__pyx_kp_TRUNC;
static PyObject *__pyx_kp_NOLCK;
static PyObject *__pyx_kp_LCKNB;


/* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":51
 * 	cdef TCIDB *db
 * 
 * 	cdef __throw_exception(self):             # <<<<<<<<<<<<<<
 * 		errcode = tcidbecode(self.db)
 * 		errmsg = tcidberrmsg(errcode)
 */

static char __pyx_k_Exception[] = "Exception";

static PyObject *__pyx_kp_Exception;

static PyObject *__pyx_builtin_Exception;

static  PyObject *__pyx_f_8dystopia_8database___throw_exception(struct __pyx_obj_8dystopia_database *__pyx_v_self) {
  PyObject *__pyx_v_errcode;
  PyObject *__pyx_v_errmsg;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  PyObject *__pyx_3 = 0;
  __pyx_v_errcode = Py_None; Py_INCREF(Py_None);
  __pyx_v_errmsg = Py_None; Py_INCREF(Py_None);

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":52
 * 
 * 	cdef __throw_exception(self):
 * 		errcode = tcidbecode(self.db)             # <<<<<<<<<<<<<<
 * 		errmsg = tcidberrmsg(errcode)
 * 		raise Exception(errmsg)
 */
  __pyx_1 = PyInt_FromLong(tcidbecode(__pyx_v_self->db)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_v_errcode);
  __pyx_v_errcode = __pyx_1;
  __pyx_1 = 0;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":53
 * 	cdef __throw_exception(self):
 * 		errcode = tcidbecode(self.db)
 * 		errmsg = tcidberrmsg(errcode)             # <<<<<<<<<<<<<<
 * 		raise Exception(errmsg)
 * 
 */
  __pyx_2 = __pyx_PyInt_int(__pyx_v_errcode); if (unlikely((__pyx_2 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_1 = __Pyx_PyBytes_FromString(tcidberrmsg(__pyx_2)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_v_errmsg);
  __pyx_v_errmsg = __pyx_1;
  __pyx_1 = 0;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":54
 * 		errcode = tcidbecode(self.db)
 * 		errmsg = tcidberrmsg(errcode)
 * 		raise Exception(errmsg)             # <<<<<<<<<<<<<<
 * 
 * 	def __init__(self):
 */
  __pyx_1 = PyTuple_New(1); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_INCREF(__pyx_v_errmsg);
  PyTuple_SET_ITEM(__pyx_1, 0, __pyx_v_errmsg);
  __pyx_3 = PyObject_Call(__pyx_builtin_Exception, ((PyObject *)__pyx_1), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(((PyObject *)__pyx_1)); __pyx_1 = 0;
  __Pyx_Raise(__pyx_3, 0, 0);
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1;}

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("dystopia.database.__throw_exception");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_errcode);
  Py_DECREF(__pyx_v_errmsg);
  return __pyx_r;
}

/* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":56
 * 		raise Exception(errmsg)
 * 
 * 	def __init__(self):             # <<<<<<<<<<<<<<
 * 		self.db = tcidbnew()
 * 
 */

static int __pyx_pf_8dystopia_8database___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_pf_8dystopia_8database___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_r;
  if (unlikely(PyTuple_GET_SIZE(__pyx_args) > 0)) {
    __Pyx_RaiseArgtupleTooLong(0, PyTuple_GET_SIZE(__pyx_args));
    return -1;
  }
  if (unlikely(__pyx_kwds)) {
    if (unlikely(!__Pyx_CheckKeywordStrings(__pyx_kwds, "__init__", 0))) return -1;
  }

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":57
 * 
 * 	def __init__(self):
 * 		self.db = tcidbnew()             # <<<<<<<<<<<<<<
 * 
 * 	def __del__(self):
 */
  ((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->db = tcidbnew();

  __pyx_r = 0;
  return __pyx_r;
}

/* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":59
 * 		self.db = tcidbnew()
 * 
 * 	def __del__(self):             # <<<<<<<<<<<<<<
 * 		tcidbdel(self.db)
 * 
 */

static PyObject *__pyx_pf_8dystopia_8database___del__(PyObject *__pyx_v_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_8dystopia_8database___del__(PyObject *__pyx_v_self, PyObject *unused) {
  PyObject *__pyx_r;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":60
 * 
 * 	def __del__(self):
 * 		tcidbdel(self.db)             # <<<<<<<<<<<<<<
 * 
 * 	def __len__(self):
 */
  tcidbdel(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->db);

  __pyx_r = Py_None; Py_INCREF(Py_None);
  return __pyx_r;
}

/* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":62
 * 		tcidbdel(self.db)
 * 
 * 	def __len__(self):             # <<<<<<<<<<<<<<
 * 		return tcidbrnum(self.db)
 * 
 */

static Py_ssize_t __pyx_pf_8dystopia_8database___len__(PyObject *__pyx_v_self); /*proto*/
static Py_ssize_t __pyx_pf_8dystopia_8database___len__(PyObject *__pyx_v_self) {
  Py_ssize_t __pyx_r;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":63
 * 
 * 	def __len__(self):
 * 		return tcidbrnum(self.db)             # <<<<<<<<<<<<<<
 * 
 * 	def open(self, filename, mode):
 */
  __pyx_r = tcidbrnum(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->db);
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":65
 * 		return tcidbrnum(self.db)
 * 
 * 	def open(self, filename, mode):             # <<<<<<<<<<<<<<
 * 		if not tcidbopen(self.db, filename, mode):
 * 			self.__throw_exception()
 */

static PyObject *__pyx_pf_8dystopia_8database_open(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_8dystopia_8database_open(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_filename = 0;
  PyObject *__pyx_v_mode = 0;
  PyObject *__pyx_r;
  char *__pyx_1;
  int __pyx_2;
  int __pyx_3;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"filename","mode",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_filename = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_mode = PyTuple_GET_ITEM(__pyx_args, 1);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_filename, &__pyx_v_mode))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("dystopia.database.open");
  return NULL;
  __pyx_L3:;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":66
 * 
 * 	def open(self, filename, mode):
 * 		if not tcidbopen(self.db, filename, mode):             # <<<<<<<<<<<<<<
 * 			self.__throw_exception()
 * 
 */
  __pyx_1 = __Pyx_PyBytes_AsString(__pyx_v_filename); if (unlikely((!__pyx_1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = __pyx_PyInt_int(__pyx_v_mode); if (unlikely((__pyx_2 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = (!tcidbopen(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->db, __pyx_1, __pyx_2));
  if (__pyx_3) {

    /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":67
 * 	def open(self, filename, mode):
 * 		if not tcidbopen(self.db, filename, mode):
 * 			self.__throw_exception()             # <<<<<<<<<<<<<<
 * 
 * 	def close(self):
 */
    __pyx_4 = ((struct __pyx_vtabstruct_8dystopia_database *)((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->__pyx_vtab)->__throw_exception(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("dystopia.database.open");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":69
 * 			self.__throw_exception()
 * 
 * 	def close(self):             # <<<<<<<<<<<<<<
 * 		if not tcidbclose(self.db):
 * 			self.__throw_exception()
 */

static PyObject *__pyx_pf_8dystopia_8database_close(PyObject *__pyx_v_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_8dystopia_8database_close(PyObject *__pyx_v_self, PyObject *unused) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":70
 * 
 * 	def close(self):
 * 		if not tcidbclose(self.db):             # <<<<<<<<<<<<<<
 * 			self.__throw_exception()
 * 
 */
  __pyx_1 = (!tcidbclose(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->db));
  if (__pyx_1) {

    /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":71
 * 	def close(self):
 * 		if not tcidbclose(self.db):
 * 			self.__throw_exception()             # <<<<<<<<<<<<<<
 * 
 * 	def path(self):
 */
    __pyx_2 = ((struct __pyx_vtabstruct_8dystopia_database *)((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->__pyx_vtab)->__throw_exception(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 71; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("dystopia.database.close");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":73
 * 			self.__throw_exception()
 * 
 * 	def path(self):             # <<<<<<<<<<<<<<
 * 		cdef char *result
 * 		result = tcidbpath(self.db)
 */

static PyObject *__pyx_pf_8dystopia_8database_path(PyObject *__pyx_v_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_8dystopia_8database_path(PyObject *__pyx_v_self, PyObject *unused) {
  char *__pyx_v_result;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":75
 * 	def path(self):
 * 		cdef char *result
 * 		result = tcidbpath(self.db)             # <<<<<<<<<<<<<<
 * 
 * 		if result == NULL:
 */
  __pyx_v_result = tcidbpath(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->db);

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":77
 * 		result = tcidbpath(self.db)
 * 
 * 		if result == NULL:             # <<<<<<<<<<<<<<
 * 			return None
 * 		else:
 */
  __pyx_1 = (__pyx_v_result == NULL);
  if (__pyx_1) {

    /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":78
 * 
 * 		if result == NULL:
 * 			return None             # <<<<<<<<<<<<<<
 * 		else:
 * 			return result
 */
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
    goto __pyx_L4;
  }
  /*else*/ {

    /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":80
 * 			return None
 * 		else:
 * 			return result             # <<<<<<<<<<<<<<
 * 
 * 	def fsiz(self):
 */
    __pyx_2 = __Pyx_PyBytes_FromString(__pyx_v_result); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1;}
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L0;
  }
  __pyx_L4:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("dystopia.database.path");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":82
 * 			return result
 * 
 * 	def fsiz(self):             # <<<<<<<<<<<<<<
 * 		return tcidbfsiz(self.db)
 * 
 */

static PyObject *__pyx_pf_8dystopia_8database_fsiz(PyObject *__pyx_v_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_8dystopia_8database_fsiz(PyObject *__pyx_v_self, PyObject *unused) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":83
 * 
 * 	def fsiz(self):
 * 		return tcidbfsiz(self.db)             # <<<<<<<<<<<<<<
 * 
 * 	def put(self, id, text):
 */
  __pyx_1 = PyLong_FromUnsignedLong(tcidbfsiz(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->db)); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 83; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("dystopia.database.fsiz");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":85
 * 		return tcidbfsiz(self.db)
 * 
 * 	def put(self, id, text):             # <<<<<<<<<<<<<<
 * 		if not tcidbput(self.db, id, text):
 * 			self.__throw_exception()
 */

static PyObject *__pyx_pf_8dystopia_8database_put(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_8dystopia_8database_put(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_id = 0;
  PyObject *__pyx_v_text = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  char *__pyx_2;
  int __pyx_3;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"id","text",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_id = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_text = PyTuple_GET_ITEM(__pyx_args, 1);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_id, &__pyx_v_text))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 85; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("dystopia.database.put");
  return NULL;
  __pyx_L3:;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":86
 * 
 * 	def put(self, id, text):
 * 		if not tcidbput(self.db, id, text):             # <<<<<<<<<<<<<<
 * 			self.__throw_exception()
 * 
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_id); if (unlikely((__pyx_1 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = __Pyx_PyBytes_AsString(__pyx_v_text); if (unlikely((!__pyx_2) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 86; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = (!tcidbput(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->db, __pyx_1, __pyx_2));
  if (__pyx_3) {

    /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":87
 * 	def put(self, id, text):
 * 		if not tcidbput(self.db, id, text):
 * 			self.__throw_exception()             # <<<<<<<<<<<<<<
 * 
 * 	def out(self, id):
 */
    __pyx_4 = ((struct __pyx_vtabstruct_8dystopia_database *)((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->__pyx_vtab)->__throw_exception(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 87; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("dystopia.database.put");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":89
 * 			self.__throw_exception()
 * 
 * 	def out(self, id):             # <<<<<<<<<<<<<<
 * 		if not tcidbout(self.db, id):
 * 			self.__throw_exception()
 */

static PyObject *__pyx_pf_8dystopia_8database_out(PyObject *__pyx_v_self, PyObject *__pyx_v_id); /*proto*/
static PyObject *__pyx_pf_8dystopia_8database_out(PyObject *__pyx_v_self, PyObject *__pyx_v_id) {
  PyObject *__pyx_r;
  int __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":90
 * 
 * 	def out(self, id):
 * 		if not tcidbout(self.db, id):             # <<<<<<<<<<<<<<
 * 			self.__throw_exception()
 * 
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_id); if (unlikely((__pyx_1 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 90; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = (!tcidbout(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->db, __pyx_1));
  if (__pyx_2) {

    /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":91
 * 	def out(self, id):
 * 		if not tcidbout(self.db, id):
 * 			self.__throw_exception()             # <<<<<<<<<<<<<<
 * 
 * 	def get(self, id):
 */
    __pyx_3 = ((struct __pyx_vtabstruct_8dystopia_database *)((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->__pyx_vtab)->__throw_exception(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("dystopia.database.out");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":93
 * 			self.__throw_exception()
 * 
 * 	def get(self, id):             # <<<<<<<<<<<<<<
 * 		cdef char *text
 * 		text = tcidbget(self.db, id)
 */

static PyObject *__pyx_pf_8dystopia_8database_get(PyObject *__pyx_v_self, PyObject *__pyx_v_id); /*proto*/
static PyObject *__pyx_pf_8dystopia_8database_get(PyObject *__pyx_v_self, PyObject *__pyx_v_id) {
  char *__pyx_v_text;
  PyObject *__pyx_r;
  int __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":95
 * 	def get(self, id):
 * 		cdef char *text
 * 		text = tcidbget(self.db, id)             # <<<<<<<<<<<<<<
 * 
 * 		if text == NULL:
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_id); if (unlikely((__pyx_1 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 95; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_v_text = tcidbget(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->db, __pyx_1);

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":97
 * 		text = tcidbget(self.db, id)
 * 
 * 		if text == NULL:             # <<<<<<<<<<<<<<
 * 			return None
 * 		else:
 */
  __pyx_2 = (__pyx_v_text == NULL);
  if (__pyx_2) {

    /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":98
 * 
 * 		if text == NULL:
 * 			return None             # <<<<<<<<<<<<<<
 * 		else:
 * 			return text
 */
    Py_INCREF(Py_None);
    __pyx_r = Py_None;
    goto __pyx_L0;
    goto __pyx_L4;
  }
  /*else*/ {

    /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":100
 * 			return None
 * 		else:
 * 			return text             # <<<<<<<<<<<<<<
 * 
 * 	def vanish(self):
 */
    __pyx_3 = __Pyx_PyBytes_FromString(__pyx_v_text); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; __pyx_clineno = __LINE__; goto __pyx_L1;}
    __pyx_r = __pyx_3;
    __pyx_3 = 0;
    goto __pyx_L0;
  }
  __pyx_L4:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("dystopia.database.get");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":102
 * 			return text
 * 
 * 	def vanish(self):             # <<<<<<<<<<<<<<
 * 		if not tcidbvanish(self.db):
 * 			self.__throw_exception()
 */

static PyObject *__pyx_pf_8dystopia_8database_vanish(PyObject *__pyx_v_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_8dystopia_8database_vanish(PyObject *__pyx_v_self, PyObject *unused) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":103
 * 
 * 	def vanish(self):
 * 		if not tcidbvanish(self.db):             # <<<<<<<<<<<<<<
 * 			self.__throw_exception()
 * 
 */
  __pyx_1 = (!tcidbvanish(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->db));
  if (__pyx_1) {

    /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":104
 * 	def vanish(self):
 * 		if not tcidbvanish(self.db):
 * 			self.__throw_exception()             # <<<<<<<<<<<<<<
 * 
 * 	def tune(self, ernum, etnum, iusiz, opts):
 */
    __pyx_2 = ((struct __pyx_vtabstruct_8dystopia_database *)((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->__pyx_vtab)->__throw_exception(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 104; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("dystopia.database.vanish");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":106
 * 			self.__throw_exception()
 * 
 * 	def tune(self, ernum, etnum, iusiz, opts):             # <<<<<<<<<<<<<<
 * 		if not tcidbtune(self.db, ernum, etnum, iusiz, opts):
 * 			self.__throw_exception()
 */

static PyObject *__pyx_pf_8dystopia_8database_tune(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_8dystopia_8database_tune(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_ernum = 0;
  PyObject *__pyx_v_etnum = 0;
  PyObject *__pyx_v_iusiz = 0;
  PyObject *__pyx_v_opts = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  int __pyx_2;
  int __pyx_3;
  unsigned char __pyx_4;
  int __pyx_5;
  PyObject *__pyx_6 = 0;
  static char *__pyx_argnames[] = {"ernum","etnum","iusiz","opts",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 4)) {
    __pyx_v_ernum = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_etnum = PyTuple_GET_ITEM(__pyx_args, 1);
    __pyx_v_iusiz = PyTuple_GET_ITEM(__pyx_args, 2);
    __pyx_v_opts = PyTuple_GET_ITEM(__pyx_args, 3);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OOOO", __pyx_argnames, &__pyx_v_ernum, &__pyx_v_etnum, &__pyx_v_iusiz, &__pyx_v_opts))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("dystopia.database.tune");
  return NULL;
  __pyx_L3:;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":107
 * 
 * 	def tune(self, ernum, etnum, iusiz, opts):
 * 		if not tcidbtune(self.db, ernum, etnum, iusiz, opts):             # <<<<<<<<<<<<<<
 * 			self.__throw_exception()
 * 
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_ernum); if (unlikely((__pyx_1 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = __pyx_PyInt_int(__pyx_v_etnum); if (unlikely((__pyx_2 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = __pyx_PyInt_int(__pyx_v_iusiz); if (unlikely((__pyx_3 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_4 = __pyx_PyInt_unsigned_char(__pyx_v_opts); if (unlikely((__pyx_4 == (unsigned char)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_5 = (!tcidbtune(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->db, __pyx_1, __pyx_2, __pyx_3, __pyx_4));
  if (__pyx_5) {

    /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":108
 * 	def tune(self, ernum, etnum, iusiz, opts):
 * 		if not tcidbtune(self.db, ernum, etnum, iusiz, opts):
 * 			self.__throw_exception()             # <<<<<<<<<<<<<<
 * 
 * 	def setcache(self, icsiz, lcnum):
 */
    __pyx_6 = ((struct __pyx_vtabstruct_8dystopia_database *)((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->__pyx_vtab)->__throw_exception(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)); if (unlikely(!__pyx_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_6); __pyx_6 = 0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_6);
  __Pyx_AddTraceback("dystopia.database.tune");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":110
 * 			self.__throw_exception()
 * 
 * 	def setcache(self, icsiz, lcnum):             # <<<<<<<<<<<<<<
 * 		if not tcidbsetcache(self.db, icsiz, lcnum):
 * 			self.__throw_exception()
 */

static PyObject *__pyx_pf_8dystopia_8database_setcache(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_pf_8dystopia_8database_setcache(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_icsiz = 0;
  PyObject *__pyx_v_lcnum = 0;
  PyObject *__pyx_r;
  int __pyx_1;
  int __pyx_2;
  int __pyx_3;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"icsiz","lcnum",0};
  if (likely(!__pyx_kwds) && likely(PyTuple_GET_SIZE(__pyx_args) == 2)) {
    __pyx_v_icsiz = PyTuple_GET_ITEM(__pyx_args, 0);
    __pyx_v_lcnum = PyTuple_GET_ITEM(__pyx_args, 1);
  }
  else {
    if (unlikely(!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "OO", __pyx_argnames, &__pyx_v_icsiz, &__pyx_v_lcnum))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 110; __pyx_clineno = __LINE__; goto __pyx_L2;}
  }
  goto __pyx_L3;
  __pyx_L2:;
  __Pyx_AddTraceback("dystopia.database.setcache");
  return NULL;
  __pyx_L3:;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":111
 * 
 * 	def setcache(self, icsiz, lcnum):
 * 		if not tcidbsetcache(self.db, icsiz, lcnum):             # <<<<<<<<<<<<<<
 * 			self.__throw_exception()
 * 
 */
  __pyx_1 = __pyx_PyInt_int(__pyx_v_icsiz); if (unlikely((__pyx_1 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = __pyx_PyInt_int(__pyx_v_lcnum); if (unlikely((__pyx_2 == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 111; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_3 = (!tcidbsetcache(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->db, __pyx_1, __pyx_2));
  if (__pyx_3) {

    /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":112
 * 	def setcache(self, icsiz, lcnum):
 * 		if not tcidbsetcache(self.db, icsiz, lcnum):
 * 			self.__throw_exception()             # <<<<<<<<<<<<<<
 * 
 * 	def setfwmmax(self, fwmmax):
 */
    __pyx_4 = ((struct __pyx_vtabstruct_8dystopia_database *)((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->__pyx_vtab)->__throw_exception(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 112; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_4); __pyx_4 = 0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("dystopia.database.setcache");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":114
 * 			self.__throw_exception()
 * 
 * 	def setfwmmax(self, fwmmax):             # <<<<<<<<<<<<<<
 * 		if not tcidbsetfwmmax(self.db, fwmmax):
 * 			self.__throw_exception()
 */

static PyObject *__pyx_pf_8dystopia_8database_setfwmmax(PyObject *__pyx_v_self, PyObject *__pyx_v_fwmmax); /*proto*/
static PyObject *__pyx_pf_8dystopia_8database_setfwmmax(PyObject *__pyx_v_self, PyObject *__pyx_v_fwmmax) {
  PyObject *__pyx_r;
  unsigned int __pyx_1;
  int __pyx_2;
  PyObject *__pyx_3 = 0;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":115
 * 
 * 	def setfwmmax(self, fwmmax):
 * 		if not tcidbsetfwmmax(self.db, fwmmax):             # <<<<<<<<<<<<<<
 * 			self.__throw_exception()
 * 
 */
  __pyx_1 = PyInt_AsUnsignedLongMask(__pyx_v_fwmmax); if (unlikely((__pyx_1 == (unsigned int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 115; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_2 = (!tcidbsetfwmmax(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->db, __pyx_1));
  if (__pyx_2) {

    /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":116
 * 	def setfwmmax(self, fwmmax):
 * 		if not tcidbsetfwmmax(self.db, fwmmax):
 * 			self.__throw_exception()             # <<<<<<<<<<<<<<
 * 
 * 	def sync(self):
 */
    __pyx_3 = ((struct __pyx_vtabstruct_8dystopia_database *)((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->__pyx_vtab)->__throw_exception(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("dystopia.database.setfwmmax");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":118
 * 			self.__throw_exception()
 * 
 * 	def sync(self):             # <<<<<<<<<<<<<<
 * 		if not tcidbsync(self.db):
 * 			self.__throw_exception()
 */

static PyObject *__pyx_pf_8dystopia_8database_sync(PyObject *__pyx_v_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_8dystopia_8database_sync(PyObject *__pyx_v_self, PyObject *unused) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":119
 * 
 * 	def sync(self):
 * 		if not tcidbsync(self.db):             # <<<<<<<<<<<<<<
 * 			self.__throw_exception()
 * 
 */
  __pyx_1 = (!tcidbsync(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->db));
  if (__pyx_1) {

    /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":120
 * 	def sync(self):
 * 		if not tcidbsync(self.db):
 * 			self.__throw_exception()             # <<<<<<<<<<<<<<
 * 
 * 	def optimize(self):
 */
    __pyx_2 = ((struct __pyx_vtabstruct_8dystopia_database *)((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->__pyx_vtab)->__throw_exception(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 120; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("dystopia.database.sync");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":122
 * 			self.__throw_exception()
 * 
 * 	def optimize(self):             # <<<<<<<<<<<<<<
 * 		if not tcidboptimize(self.db):
 * 			self.__throw_exception()
 */

static PyObject *__pyx_pf_8dystopia_8database_optimize(PyObject *__pyx_v_self, PyObject *unused); /*proto*/
static PyObject *__pyx_pf_8dystopia_8database_optimize(PyObject *__pyx_v_self, PyObject *unused) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":123
 * 
 * 	def optimize(self):
 * 		if not tcidboptimize(self.db):             # <<<<<<<<<<<<<<
 * 			self.__throw_exception()
 * 
 */
  __pyx_1 = (!tcidboptimize(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->db));
  if (__pyx_1) {

    /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":124
 * 	def optimize(self):
 * 		if not tcidboptimize(self.db):
 * 			self.__throw_exception()             # <<<<<<<<<<<<<<
 * 
 */
    __pyx_2 = ((struct __pyx_vtabstruct_8dystopia_database *)((struct __pyx_obj_8dystopia_database *)__pyx_v_self)->__pyx_vtab)->__throw_exception(((struct __pyx_obj_8dystopia_database *)__pyx_v_self)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; __pyx_clineno = __LINE__; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    goto __pyx_L4;
  }
  __pyx_L4:;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("dystopia.database.optimize");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_kp___init__, __pyx_k___init__, sizeof(__pyx_k___init__), 0, 1, 1},
  {&__pyx_kp___del__, __pyx_k___del__, sizeof(__pyx_k___del__), 0, 1, 1},
  {&__pyx_kp___len__, __pyx_k___len__, sizeof(__pyx_k___len__), 0, 1, 1},
  {&__pyx_kp_open, __pyx_k_open, sizeof(__pyx_k_open), 0, 1, 1},
  {&__pyx_kp_close, __pyx_k_close, sizeof(__pyx_k_close), 0, 1, 1},
  {&__pyx_kp_path, __pyx_k_path, sizeof(__pyx_k_path), 0, 1, 1},
  {&__pyx_kp_fsiz, __pyx_k_fsiz, sizeof(__pyx_k_fsiz), 0, 1, 1},
  {&__pyx_kp_put, __pyx_k_put, sizeof(__pyx_k_put), 0, 1, 1},
  {&__pyx_kp_out, __pyx_k_out, sizeof(__pyx_k_out), 0, 1, 1},
  {&__pyx_kp_get, __pyx_k_get, sizeof(__pyx_k_get), 0, 1, 1},
  {&__pyx_kp_vanish, __pyx_k_vanish, sizeof(__pyx_k_vanish), 0, 1, 1},
  {&__pyx_kp_tune, __pyx_k_tune, sizeof(__pyx_k_tune), 0, 1, 1},
  {&__pyx_kp_setcache, __pyx_k_setcache, sizeof(__pyx_k_setcache), 0, 1, 1},
  {&__pyx_kp_setfwmmax, __pyx_k_setfwmmax, sizeof(__pyx_k_setfwmmax), 0, 1, 1},
  {&__pyx_kp_sync, __pyx_k_sync, sizeof(__pyx_k_sync), 0, 1, 1},
  {&__pyx_kp_optimize, __pyx_k_optimize, sizeof(__pyx_k_optimize), 0, 1, 1},
  {&__pyx_kp_READER, __pyx_k_READER, sizeof(__pyx_k_READER), 1, 1, 1},
  {&__pyx_kp_WRITER, __pyx_k_WRITER, sizeof(__pyx_k_WRITER), 1, 1, 1},
  {&__pyx_kp_CREAT, __pyx_k_CREAT, sizeof(__pyx_k_CREAT), 1, 1, 1},
  {&__pyx_kp_TRUNC, __pyx_k_TRUNC, sizeof(__pyx_k_TRUNC), 1, 1, 1},
  {&__pyx_kp_NOLCK, __pyx_k_NOLCK, sizeof(__pyx_k_NOLCK), 1, 1, 1},
  {&__pyx_kp_LCKNB, __pyx_k_LCKNB, sizeof(__pyx_k_LCKNB), 1, 1, 1},
  {&__pyx_kp_Exception, __pyx_k_Exception, sizeof(__pyx_k_Exception), 1, 1, 1},
  {0, 0, 0, 0, 0}
};
static struct __pyx_vtabstruct_8dystopia_database __pyx_vtable_8dystopia_database;

static PyObject *__pyx_tp_new_8dystopia_database(PyTypeObject *t, PyObject *a, PyObject *k) {
  struct __pyx_obj_8dystopia_database *p;
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  p = ((struct __pyx_obj_8dystopia_database *)o);
  *(struct __pyx_vtabstruct_8dystopia_database **)&p->__pyx_vtab = __pyx_vtabptr_8dystopia_database;
  return o;
}

static void __pyx_tp_dealloc_8dystopia_database(PyObject *o) {
  (*Py_TYPE(o)->tp_free)(o);
}

static struct PyMethodDef __pyx_methods_8dystopia_database[] = {
  {"__del__", (PyCFunction)__pyx_pf_8dystopia_8database___del__, METH_NOARGS, 0},
  {"open", (PyCFunction)__pyx_pf_8dystopia_8database_open, METH_VARARGS|METH_KEYWORDS, 0},
  {"close", (PyCFunction)__pyx_pf_8dystopia_8database_close, METH_NOARGS, 0},
  {"path", (PyCFunction)__pyx_pf_8dystopia_8database_path, METH_NOARGS, 0},
  {"fsiz", (PyCFunction)__pyx_pf_8dystopia_8database_fsiz, METH_NOARGS, 0},
  {"put", (PyCFunction)__pyx_pf_8dystopia_8database_put, METH_VARARGS|METH_KEYWORDS, 0},
  {"out", (PyCFunction)__pyx_pf_8dystopia_8database_out, METH_O, 0},
  {"get", (PyCFunction)__pyx_pf_8dystopia_8database_get, METH_O, 0},
  {"vanish", (PyCFunction)__pyx_pf_8dystopia_8database_vanish, METH_NOARGS, 0},
  {"tune", (PyCFunction)__pyx_pf_8dystopia_8database_tune, METH_VARARGS|METH_KEYWORDS, 0},
  {"setcache", (PyCFunction)__pyx_pf_8dystopia_8database_setcache, METH_VARARGS|METH_KEYWORDS, 0},
  {"setfwmmax", (PyCFunction)__pyx_pf_8dystopia_8database_setfwmmax, METH_O, 0},
  {"sync", (PyCFunction)__pyx_pf_8dystopia_8database_sync, METH_NOARGS, 0},
  {"optimize", (PyCFunction)__pyx_pf_8dystopia_8database_optimize, METH_NOARGS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_database = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_divide*/
  #endif
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_coerce*/
  #endif
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_oct*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*nb_hex*/
  #endif
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_inplace_divide*/
  #endif
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if (PY_MAJOR_VERSION >= 3) || (Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX)
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_database = {
  __pyx_pf_8dystopia_8database___len__, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_database = {
  __pyx_pf_8dystopia_8database___len__, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_database = {
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getreadbuffer*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getwritebuffer*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getsegcount*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getcharbuffer*/
  #endif
  #if (PY_MAJOR_VERSION >= 3) || (Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_NEWBUFFER)
  0, /*bf_getbuffer*/
  #endif
  #if (PY_MAJOR_VERSION >= 3) || (Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_NEWBUFFER)
  0, /*bf_releasebuffer*/
  #endif
};

PyTypeObject __pyx_type_8dystopia_database = {
  PyVarObject_HEAD_INIT(0, 0)
  "dystopia.database", /*tp_name*/
  sizeof(struct __pyx_obj_8dystopia_database), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_8dystopia_database, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  0, /*tp_repr*/
  &__pyx_tp_as_number_database, /*tp_as_number*/
  &__pyx_tp_as_sequence_database, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_database, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  0, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_database, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_8dystopia_database, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_pf_8dystopia_8database___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_8dystopia_database, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

PyMODINIT_FUNC initdystopia(void); /*proto*/
PyMODINIT_FUNC initdystopia(void) {
  PyObject *__pyx_1 = 0;
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;}
  /*--- Libary function declarations ---*/
  __pyx_init_filenames();
  /*--- Module creation code ---*/
  __pyx_m = Py_InitModule4("dystopia", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;};
  Py_INCREF(__pyx_m);
  __pyx_b = PyImport_AddModule(__Pyx_BUILTIN_MODULE_NAME);
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- Intern code ---*/
  /*--- String init code ---*/
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2; __pyx_clineno = __LINE__; goto __pyx_L1;};
  /*--- Builtin init code ---*/
  __pyx_builtin_Exception = __Pyx_GetName(__pyx_b, __pyx_kp_Exception); if (!__pyx_builtin_Exception) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  __pyx_vtabptr_8dystopia_database = &__pyx_vtable_8dystopia_database;
  *(void(**)(void))&__pyx_vtable_8dystopia_database.__throw_exception = (void(*)(void))__pyx_f_8dystopia_8database___throw_exception;
  if (PyType_Ready(&__pyx_type_8dystopia_database) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (__Pyx_SetVtable(__pyx_type_8dystopia_database.tp_dict, __pyx_vtabptr_8dystopia_database) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "database", (PyObject *)&__pyx_type_8dystopia_database) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1;}
  __pyx_ptype_8dystopia_database = &__pyx_type_8dystopia_database;
  /*--- Type import code ---*/
  /*--- Function import code ---*/
  /*--- Execution code ---*/

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":41
 * # Open flags
 * 
 * READER = IDBOREADER             # <<<<<<<<<<<<<<
 * WRITER = IDBOWRITER
 * CREAT = IDBOCREAT
 */
  __pyx_1 = PyInt_FromLong(IDBOREADER); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_READER, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":42
 * 
 * READER = IDBOREADER
 * WRITER = IDBOWRITER             # <<<<<<<<<<<<<<
 * CREAT = IDBOCREAT
 * TRUNC = IDBOTRUNC
 */
  __pyx_1 = PyInt_FromLong(IDBOWRITER); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_WRITER, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 42; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":43
 * READER = IDBOREADER
 * WRITER = IDBOWRITER
 * CREAT = IDBOCREAT             # <<<<<<<<<<<<<<
 * TRUNC = IDBOTRUNC
 * NOLCK = IDBONOLCK
 */
  __pyx_1 = PyInt_FromLong(IDBOCREAT); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_CREAT, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":44
 * WRITER = IDBOWRITER
 * CREAT = IDBOCREAT
 * TRUNC = IDBOTRUNC             # <<<<<<<<<<<<<<
 * NOLCK = IDBONOLCK
 * LCKNB = IDBOLCKNB
 */
  __pyx_1 = PyInt_FromLong(IDBOTRUNC); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_TRUNC, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":45
 * CREAT = IDBOCREAT
 * TRUNC = IDBOTRUNC
 * NOLCK = IDBONOLCK             # <<<<<<<<<<<<<<
 * LCKNB = IDBOLCKNB
 * 
 */
  __pyx_1 = PyInt_FromLong(IDBONOLCK); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_NOLCK, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":46
 * TRUNC = IDBOTRUNC
 * NOLCK = IDBONOLCK
 * LCKNB = IDBOLCKNB             # <<<<<<<<<<<<<<
 * 
 * cdef class database:
 */
  __pyx_1 = PyInt_FromLong(IDBOLCKNB); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; __pyx_clineno = __LINE__; goto __pyx_L1;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LCKNB, __pyx_1) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; __pyx_clineno = __LINE__; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;

  /* "/home/fraggle/projects/cython/pytokyodystopia/dystopia.pyx":122
 * 			self.__throw_exception()
 * 
 * 	def optimize(self):             # <<<<<<<<<<<<<<
 * 		if not tcidboptimize(self.db):
 * 			self.__throw_exception()
 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("dystopia");
}

static const char *__pyx_filenames[] = {
  "dystopia.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static INLINE void __Pyx_RaiseArgtupleTooLong(
    Py_ssize_t num_expected,
    Py_ssize_t num_found)
{
    const char* error_message =
    #if PY_VERSION_HEX < 0x02050000
        "function takes at most %d positional arguments (%d given)";
    #else
        "function takes at most %zd positional arguments (%zd given)";
    #endif
    PyErr_Format(PyExc_TypeError, error_message, num_expected, num_found);
}

static int __Pyx_CheckKeywordStrings(
    PyObject *kwdict,
    const char* function_name,
    int kw_allowed)
{
    PyObject* key = 0;
    Py_ssize_t pos = 0;
    while (PyDict_Next(kwdict, &pos, &key, 0)) {
        #if PY_MAJOR_VERSION < 3
        if (unlikely(!PyString_Check(key))) {
        #else
        if (unlikely(!PyUnicode_Check(key))) {
        #endif
            PyErr_Format(PyExc_TypeError,
                         "%s() keywords must be strings", function_name);
            return 0;
        }
    }
    if (unlikely(!kw_allowed) && unlikely(key)) {
        PyErr_Format(PyExc_TypeError,
                     "'%s' is an invalid keyword argument for this function",
        #if PY_MAJOR_VERSION < 3
                     PyString_AsString(key));
        #else
                     PyUnicode_AsString(key));
        #endif
        return 0;
    }
    return 1;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
    Py_XINCREF(type);
    Py_XINCREF(value);
    Py_XINCREF(tb);
    /* First, check the traceback argument, replacing None with NULL. */
    if (tb == Py_None) {
        Py_DECREF(tb);
        tb = 0;
    }
    else if (tb != NULL && !PyTraceBack_Check(tb)) {
        PyErr_SetString(PyExc_TypeError,
            "raise: arg 3 must be a traceback or None");
        goto raise_error;
    }
    /* Next, replace a missing value with None */
    if (value == NULL) {
        value = Py_None;
        Py_INCREF(value);
    }
    #if PY_VERSION_HEX < 0x02050000
    if (!PyClass_Check(type))
    #else
    if (!PyType_Check(type))
    #endif
    {
        /* Raising an instance.  The value should be a dummy. */
        if (value != Py_None) {
            PyErr_SetString(PyExc_TypeError,
                "instance exception may not have a separate value");
            goto raise_error;
        }
        /* Normalize to raise <class>, <instance> */
        Py_DECREF(value);
        value = type;
        #if PY_VERSION_HEX < 0x02050000
            if (PyInstance_Check(type)) {
                type = (PyObject*) ((PyInstanceObject*)type)->in_class;
                Py_INCREF(type);
            }
            else {
                type = 0;
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception must be an old-style class or instance");
                goto raise_error;
            }
        #else
            type = (PyObject*) Py_TYPE(type);
            Py_INCREF(type);
            if (!PyType_IsSubtype((PyTypeObject *)type, (PyTypeObject *)PyExc_BaseException)) {
                PyErr_SetString(PyExc_TypeError,
                    "raise: exception class must be a subclass of BaseException");
                goto raise_error;
            }
        #endif
    }
    PyErr_Restore(type, value, tb);
    return;
raise_error:
    Py_XDECREF(value);
    Py_XDECREF(type);
    Py_XDECREF(tb);
    return;
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        #if PY_MAJOR_VERSION < 3
        if (t->is_unicode && (!t->is_identifier)) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else if (t->intern) {
            *t->p = PyString_InternFromString(t->s);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        #else  /* Python 3+ has unicode identifiers */
        if (t->is_identifier || (t->is_unicode && t->intern)) {
            *t->p = PyUnicode_InternFromString(t->s);
        } else if (t->is_unicode) {
            *t->p = PyUnicode_FromStringAndSize(t->s, t->n - 1);
        } else {
            *t->p = PyBytes_FromStringAndSize(t->s, t->n - 1);
        }
        #endif
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

static int __Pyx_SetVtable(PyObject *dict, void *vtable) {
    PyObject *pycobj = 0;
    int result;
    
    pycobj = PyCObject_FromVoidPtr(vtable, 0);
    if (!pycobj)
        goto bad;
    if (PyDict_SetItemString(dict, "__pyx_vtable__", pycobj) < 0)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(const char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;

    #if PY_MAJOR_VERSION < 3
    py_srcfile = PyString_FromString(__pyx_filename);
    #else
    py_srcfile = PyUnicode_FromString(__pyx_filename);
    #endif
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromFormat( "%s (%s:%u)", funcname, __pyx_cfilenm, __pyx_clineno);
        #else
        py_funcname = PyUnicode_FromFormat( "%s (%s:%u)", funcname, __pyx_cfilenm, __pyx_clineno);
        #endif
    }
    else {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromString(funcname);
        #else
        py_funcname = PyUnicode_FromString(funcname);
        #endif
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    #if PY_MAJOR_VERSION < 3
    empty_string = PyString_FromStringAndSize("", 0);
    #else
    empty_string = PyBytes_FromStringAndSize("", 0);
    #endif
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        #if PY_MAJOR_VERSION >= 3
        0,            /*int kwonlyargcount,*/
        #endif
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_Get(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}
